print("Задача №1")
print("Применить методы кортежей")
print(sep="\n\n")
print('Метод кортежа: "count"')
print(sep="\n\n")

numbers = (1,2,4,6,8,5,3,6,7,9,6,4,3,6,8,9,3,6,3,5,7,4,3,6,7,7,5,4,3,6,6,8,5,3,2,6)
print('Список цифр', numbers)
seven = numbers.count(7)
print('Количество цифр 7 в списке равно:', seven)
five = numbers.count(5)
print('Количество цифр 5 в списке равно:', five)
six = numbers.count(6)
print('Количество цифр 6 в списке равно:', six)
three = numbers.count(3)
print('Количество цифр 3 в списке равно:', three)

print(sep="\n\n")
print('Метод кортежа: "index"')
print(sep="\n\n")

print('Список цифр', numbers)
seven = numbers.index(7)
print('Индекс цифры 7 в списке равно:', seven)
five = numbers.index(5)
print('Индекс цифры 5 в списке равно:', five)
six = numbers.index(6)
print('Индекс цифры 6 в списке равно:', six)
three = numbers.index(3)
print('Индекс цифры 3 в списке равно:', three)
